id: Claroty CVE - Test
inputs: []
name: Claroty CVE - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 60ea7678-e86e-4561-8c35-32c88c533065
      iscommand: false
      name: ''
      version: -1
      description: ''
    taskid: 60ea7678-e86e-4561-8c35-32c88c533065
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 77b395d9-afc4-48ca-8d46-7d7306b2353e
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: 77b395d9-afc4-48ca-8d46-7d7306b2353e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  '2':
    id: '2'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    note: false
    separatecontext: true
    task:
      brand: ''
      id: b51f0f5a-c756-49e8-8188-ff1ae4c364e8
      iscommand: false
      name: Claroty Manage Asset CVEs
      playbookName: Claroty Manage Asset CVEs
      type: playbook
      version: -1
      description: ''
    taskid: b51f0f5a-c756-49e8-8188-ff1ae4c364e8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
description: ''
fromversion: 5.0.0
